name: Artifacts upload pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create application file
        run: echo "This is the testing code" > app.js

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-artifact
          path: app.js
