name: Hello World

on:
  pull_request:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Testing the hello world script
        run: echo "Welcome to the 1st Job"
