on:
  pull_request: 
    branches:
      - main

jobs:
  Deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment:
          - dev
          - qa
          - prod

    steps:
      - name: Deployment to different environment
        run: echo "Deploying to ${{ matrix.environment }}"
