name: Secrets Demo

on:
  pull_request:
    branches:
      - main

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Use the secret
        run: echo "The secret value is ${{ secrets.MY_SECRET_KEY }}"
