name: External Integration

on:
  push:
    branches:
      - main
 
jobs:
  external-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Notification via curl request
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"text":"Hello from GitHub Actions! From Raj 🚀"}' \
            "${{ secrets.WEBHOOK }}"
